server:
  port: 8080

spring:
  application:
    name: SpringSecurityClient

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
